In [1]:
# %load_ext autoreload
# %autoreload 2
import os, sys

import scanpy as sc
import anndata as ad
import numpy as np

import torch
from torch import nn
from matplotlib import pyplot as plt
from torch.utils.data import DataLoader

/home/wergillius/.conda/envs/GenDiff/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [20]:
tf_atlas_path = "/home/wergillius/Project/diffuse_differentiate/data/TFAtlas/GSE217460_210322_TFAtlas.h5ad"
if os.path.exists(tf_atlas_path):
    adata = sc.read_h5ad(tf_atlas_path)
else:
    print("FILE NOT FOUND")

True

In [3]:
tf_atlas_path = "/home/wergillius/Project/diffuse_differentiate/data/TFAtlas/GSE217460_210322_TFAtlas_subsample.h5ad"
if os.path.exists(tf_atlas_path):
    adata = sc.read_h5ad(tf_atlas_path)
else:
    print("FILE NOT FOUND")

In [5]:
adata.uns['iroot']

417135

In [18]:
unique_conditions = np.unique([x.split("-")[1] for x in adata.obs['TF'].unique()])

In [20]:
'mCherry' in unique_conditions

True

In [21]:
'GFP' in unique_conditions

True

In [10]:
adata.X.mean(axis=0)

array([-4.2805612e-09, -1.6606492e-08, -1.6932544e-08, ...,
       -4.1946322e-09, -3.2966650e-08,  6.5354877e-09], dtype=float32)

In [11]:
adata.X.max(axis=0)

array([4.3417835, 4.327071 , 4.808628 , ..., 8.174618 , 4.7162957,
       4.2594876], dtype=float32)

In [12]:
adata.X.min(axis=0)

array([-1.4282931, -1.5349555, -1.2466139, ..., -0.7380165, -1.3647482,
       -1.541671 ], dtype=float32)